### ISSUE TITLE
Problem with GetPaymentResponse $p->consumer->shippingAddress

### ISSUE THREAD

**Issue by capm4** [Nets-eCom/Magento2_easy#13]
In my case , I get such response in Dibs\EasyCheckout\Model\Client\DTO\GetPaymentResponse

so all importent field I make with * 

my responce 
{"payment":{"paymentId":"*****","summary":{"reservedAmount":***},"consumer":{"company":{"contactDetails":{"phoneNumber":{}}},"privatePerson":{"phoneNumber":{}},"billingAddress":{}},"paymentDetails":{"paymentType":"CARD","paymentMethod":"MasterCard","invoiceDetails":{},"cardDetails":{"maskedPan":"******","expiryDate":"****"}},"orderDetails":{"amount":400,"currency":"EUR","reference":"quote_id_4494"},"checkout":{"url":"******"},"created":"2021-04-23T14:14:27.5762+00:00"}}

And for this I get error : dibs.ERROR: Exception: Notice: Undefined property: stdClass::$shippingAddress in /dibs/easycheckout/Model/Client/DTO/GetPaymentResponse.php(91) 

And as you see in response no shippingAddress.
My question is should I get shippingAddress or we need to update filed 91 
from : if (!empty((array)$p->consumer->shippingAddress)) { 
TO : if (isset($p->consumer->shippingAddress) && !empty((array)$p->consumer->shippingAddress)) {

**Comment by martinSternelius** [comment]
Hi. Could you provide a more detailed explanation of how to reproduce this issue? Including module version, Magento version, and module config values.

**Comment by sursi** [comment]
Hi All,

Kindly upgrade to the latest version and let us know if you are still facing the same issue as we are not able to reproduce this in our test environment.

Have a nice day.

Sincerely,
Surjan
