### ISSUE TITLE
Multisite not supported!!

### ISSUE THREAD

**Issue by JKSkog** [Nets-eCom/Magento2_easy#2]
When trying to capture the Innvoice online in admin, the module uses only the default checkout key and secret, resulting in a 401 Unauthorized` response. and cannot capture. 
One can only capture if the default cridentials is the same as wesite cridentials !! Please chek asap.

**Comment by adamnwt** [comment]
Hello @JKSkog we will look in to this and hopefully have a solution for this shortly.

**Comment by sursi** [comment]
Hi @JKSkog, This issue has been fixed, kindly upgrade to latest version.

Have a nice day.

Sincerely,
Surjan,
Nets
