### ISSUE TITLE
CSP and other errors in browser-console

### ISSUE THREAD

**Issue by roman204** [Nets-eCom/Magento2_easy#20]
I get the following js-error in my browser-console with easy checkout:
`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-NzNw/hrx7wC5UKemwLm4mwVnoDVfHDuSpmZAeKCQaqY=' 'sha256-aKaLBqGLMQ35mP/i/QmpW+s6QnrN3dNb78G9ndv1bC0=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='". Either the 'unsafe-inline' keyword, a hash ('sha256-1XgMsIi6szxMi7JX5ZCg4KWReddGOu15C+cKuzlVaf4='), or a nonce ('nonce-...') is required to enable inline execution.`

see also a screenshot of the errors:

![image](https://user-images.githubusercontent.com/584168/123405782-750ee880-d5aa-11eb-9a34-727f7766816a.png)

version of module is: 1.3.1
magento version: 2.4.1
nets-checkout testmode: yes
checkout-flow: vanilla embedded

Also i am missing the configuration for allowed countries like shown in the [documentation](https://tech.nets.eu/hubfs/Magento%202%20end-to-end%20guide_Nets.pdf) on page 5 (step 3) 

No one else have those errors?

**Comment by sursi** [comment]
Hi All,

Kindly update to the latest version. Have a nice day.

Sincerely,
Surjan
