### ISSUE TITLE
PHP Linting error

### ISSUE THREAD

**Issue by snkBarryKrein** [Nets-eCom/Magento2_easy#21]
https://github.com/DIBS-Payment-Services/Magento2_easy/blob/a65400e4dce8cc1ac135d4282d49ec338fe01025/Controller/Order/ConfirmOrder.php#L52

https://github.com/DIBS-Payment-Services/Magento2_easy/blob/a65400e4dce8cc1ac135d4282d49ec338fe01025/Controller/Order/SaveOrder.php#L59

https://github.com/DIBS-Payment-Services/Magento2_easy/blob/a65400e4dce8cc1ac135d4282d49ec338fe01025/Model/Dibs/Order.php#L206

php -l throws errors here for PHP 7.2,

Linted with PHP 7.2.29 (cli)

**Comment by sursi** [comment]
@snkBarryKrein, Kindly upgrade to latest version(1.5.9). This issue has been fixed.
