### ISSUE TITLE
Problem with Uni-faun shipping method. It's not coming in dibs checkout page. 

### ISSUE THREAD

**Issue by jayantakr1** [Nets-eCom/Magento2_easy#25]
I have set checkout option "Embedded", when i am changing "Vanilla embedded" checkout it's redirecting default checkout.

I need dibs easycheckout. 

ISSUE 1: 
Order place working fine with mageno default shipping, But your easy checkout extension not calling Unifan shipping Method . Our main requirement is we need unifaun shipping method. I have checked your easy checkout features there have unifaun shipping method option in admin and fronetnd code but it's not calling in frontend. When user update address in easycheckout interface, estimate shipping method not calling and not updating shipping methods section block on easy checkout.

Note: Unifan coming in cart page. screen-shot: https://nimb.ws/tTDOpy based on zip code
Easy Checkout page unifaun not coming. screen-shot: https://nimb.ws/s8JFL3

ISSUE 2: 
I am getting below error in easy checkout. 

 Refused to load the script 'https://www.google-analytics.com/plugins/ua/ec.js' because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-NzNw/hrx7wC5UKemwLm4mwVnoDVfHDuSpmZAeKCQaqY=' 'sha256-aKaLBqGLMQ35mP/i/QmpW+s6QnrN3dNb78G9ndv1bC0=' 'sha256-1XgMsIi6szxMi7JX5ZCg4KWReddGOu15C+cKuzlVaf4='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

When i am updating address with zip code i am getting below error. 
Access to XMLHttpRequest at 'https://test.checkout.dibspayment.eu/api/v1/theming/checkout' from origin 'https://roundup-stage.digitalplattform.se' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
checkout.js?v=1:1 GET https://test.checkout.dibspayment.eu/api/v1/theming/checkout net::ERR_FAILED

ISSUE 3 : 

When i am setting "Vanilla Embeded" checkout it's redirecting default checkout not easycheckout page.

**Comment by sursi** [comment]
Hi All,

The Embedded flow in the older version is not supported now, We will request you to update to latest version.

Have a nice day.

Sincerely,
Surjan
