### ISSUE TITLE
Invoice not created

### ISSUE THREAD

**Issue by bardkalbakk** [Nets-eCom/Magento2_easy#27]
Magento 2.4.3-p1

Invoice is not being created, but the payment is captured and the transaction is created.

I have tried with a combination of _Capture Payment_ and _Auto capture_ to no avail. If you point me in the direction of where the invoice is being created I can do some debugging with xdebug.

**Comment by sursi** [comment]
Hi All,

The invoice is not created automatically by the module.

Sincerely,
Surjan
