### ISSUE TITLE
Original price = 0

### ISSUE THREAD

**Issue by sweikas** [Nets-eCom/Magento2_easy#28]
Hey,

I've noticed strange behaviour with nets easy module, after placing an order using nets as payment option, order item original price is always = 0. Replicated this behaviour on magento 2.4.1 and 2.4.3.
![image](https://user-images.githubusercontent.com/8791996/143868460-3a51714c-e44b-4cfb-9a3f-36f746d4e979.png)
This is definitely not a correct behaviour as far as I know and I think this is caused by not calling collectTotals() before converting quote to order here -> https://github.com/Nets-eCom/Magento2_easy/blob/ecc8981346cfb5a057645b08601ef6d3642d3f07/Model/Checkout.php#L651-L661 If I replace this line `$quote->setTotalsCollectedFlag(true);` with `$quote->collectTotals();` original price is set correctly as expected. Do you have any particular reason for not calling collectTotals there ? Also if collecting totals there isn't an option, how can we resolve this issue so original item price on order wouldn't be 0 ?

**Comment by sursi** [comment]
Hi,

We have fixed this issue in latest version 1.4.6 released on GitHub and Magento Marketplace, please upgrade to latest version.
Also please re-enter secret key and checkout key in Nets configuration page if found missing as we also made changes in configuration page in latest version.

Sincerely,
Surjan Singh,
Nets
