### ISSUE TITLE
Missing shipping method default selection

### ISSUE THREAD

**Issue by JKSkog** [Nets-eCom/Magento2_easy#3]
In frontend the selection of shipping method under /easycheckout/ has to be improoved. No default shipping method is selected, and since its presented in a styled box, apposed to a radio, users dont understand that one needs to click the shipping method box to see the go to payment button.
One shipping method should be selected by default.

**Comment by sursi** [comment]
Hi All,

Kindly update to the latest version. Have a nice day.

Sincerely,
Surjan
