### ISSUE TITLE
Vanilla flow bug - order addresses are empty

### ISSUE THREAD

**Issue by unicoder88** [Nets-eCom/Magento2_easy#32]
Preconditions:

- module version 1.4.6
- Handle customer data: no
- Split billing and shipping addresses: no
- Checkout flow: embedded
- Enable Auto-capture: no

After placing an order, order billing and shipping addresses are empty. Reason - but somewhere in \Dibs\EasyCheckout\Model\Checkout::placeOrder:

```PHP
// When embedded flow is used we let nets handle customer data, if redirect flow is used then we handle it.
// when the solution is hosted, the checkout url is not matching our checkout url!
$weHandleConsumerData = false;
if ($this->getHelper()->getCheckoutUrl() !== $dibsPayment->getCheckoutUrl()) {
    $weHandleConsumerData = true;
}
```

In my case this renders to:
```PHP
$weHandleConsumerData = false;
if ("/easycheckout" !== "/checkout") {
    $weHandleConsumerData = true;
}
```

So it ignores order address in Easy, and uses Magento quote billing/shipping addresses :(

**Comment by sursi** [comment]
Hi All,

If Handle customer data is set to No the customer is expected to enter the same address.

Sincerely,
Surjan
