### ISSUE TITLE
Nets Easy checkout test environment is not working

### ISSUE THREAD

**Issue by bitforbucket** [Nets-eCom/Magento2_easy#37]
Test environment https://test.checkout.dibspayment.eu/hostedpaymentpage/ is not working anymore, we get white page after redirecting from checkout. Seems like you have CSP issues. We get this errors in console:

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)
Content Security Policy: The page’s settings blocked the loading of a resource at https://checkout.s.easy.nets.eu/api/v1/theming/checkout (“default-src”). 
Content Security Policy: The page’s settings blocked the loading of a resource at https://checkout.s.easy.nets.eu/v1/assets/css/checkout.css (“default-src”).

**Comment by sursi** [comment]
Hi,

Test environment working fine now. If you still face any issue regarding this kindly raise a ticket or write an email as this issue does not come under plugin.

Thank you.
