### ISSUE TITLE
PHP8.1 strlen()

### ISSUE THREAD

**Issue by ap-bw** [Nets-eCom/Magento2_easy#40]
This will sometimes result in a fault

Deprecated Functionality: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/xxxxxxxxxxxxxx/EasyCheckout/Model/Dibs/Items.php on line 495

**Comment by sursi** [comment]
Hi @ap-bw, thanks for letting us know the issue, can you please let us know the PHP and Magento version where this issue is occurring.

**Comment by ap-bw** [comment]
PHP8.1 Magento 2.4.4
