### ISSUE TITLE
Order without payment!

### ISSUE THREAD

**Issue by jontesamuelsson** [Nets-eCom/Magento2_easy#42]
Bug: 
Customer order has passed through the payment step and created a new order in Magento despite the payment not being approved by Nets. In Nets Easy Portal no name or payment method are displayed. (blank fields). Nets Easy Portal says no payment method has been selected. 

Expected scenario:
No new order should be created in Magento as long as the order's payment has not been approved by Nets.

This happened on:
Payment ID: 00bc00006459a1f4495ccb20eb387c8a

Using plugin v. 1.6.2 on Magento 2.4.5-p2

**Comment by bitforbucket** [comment]
any estimation when this will be fixed ?

**Comment by thanhlethai** [comment]
Hi @jontesamuelsson, @bitforbucket,

Please contact our Support for this at: https://developer.nexigroup.com/nexi-checkout/en-EU/support/.
