### ISSUE TITLE
Issue during checkout with PHP 8.1

### ISSUE THREAD

**Issue by zhulak** [Nets-eCom/Magento2_easy#44]
Hi,

I get this error message during checkout when pressing "Nets Easy Checkout" button in checkout on payment step:

preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated in app/code/Dibs/EasyCheckout/Helper/Data.php on line 708

Expected Results:
- User is redirected to Nets Easy payment for finaliation of order

Additional information:
- Magento Open Source 2.4.6
- PHP 8.1
- I followed the installation guide, created a Nets Easy account and configured the test codes in Magento admin
- Using 'Redirect' checkout flow

**Comment by thanhlethai** [comment]
Hi @zhulak,

Please contact our Support for this at: https://developer.nexigroup.com/nexi-checkout/en-EU/support/.
