### ISSUE TITLE
Vipps orders are cancelled

### ISSUE THREAD

**Issue by bitforbucket** [Nets-eCom/Magento2_easy#45]
After payment success some Vipps orders are cancelled in Magento backend after some time (1-2 days). Is this a known issue?
When it will be possible to test Vipps orders using nets test environment?

Magento 2.4.5-p2
Nets easy module 1.6.2
Nets Checkout flow "Redirect"

**Comment by thanhlethai** [comment]
Hi @bitforbucket.

Please contact our Support for this at: https://developer.nexigroup.com/nexi-checkout/en-EU/support/.
