### ISSUE TITLE
Updating package name is not a patch version(!)

### ISSUE THREAD

**Issue by Andrii-Antoniuk** [Nets-eCom/Magento2_easy#48]
Hello guys! @wellfix @dominik.brozyna

#### I'll be a little toxic rn, sorry for that :) 

Just so you know, renaming a package is not a patch version update(!) 👎 
With this, you break module resolution for everybody who has version set to ^1.6 😞 

If you want to update module completely, deprecate the old one and suggest updating to new one.
Or, at least, do a major (v2.x.x) update!

**Comment by thanhlethai** [comment]
Hi @Andrii-Antoniuk,

Thanks for your feedback on this. We will take this into account for next time.

CC @wellfix, @slawro
