### ISSUE TITLE
PHP 8.x Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by micheleo** [Nets-eCom/Magento2_easy#49]
The following files have this warning, making exceptions be thrown on envs with stricter error policy. 

- Model/Client/DTO/Payment/ConsumerCompany.php
firstname
lastname

- Block/Adminhtml/System/Config/Editor.php
_wysiwygConfig

- Block/Thankyou.php
_order

- Controller/Webhook/Webhook.php
helper
paymentApi

**Comment by thanhlethai** [comment]
Hi @micheleo,

Thank you for your feedback. We are planning on a new release very soon and this will be amended and fixed in this v.1.6.7.

Best,
eCom Nets | Nexi team
